<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>Xio.Parallax.Client.Examples.GettingStarted</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Xio.Parallax.Client/Xio.Parallax.Client.csproj" />
  </ItemGroup>
</Project>
